mount: Verify mount failure in mount.glusterfs wrapper.
The result of mount command execution is not checked properly, thus
no proper message given for the end user. This patch fix the same.

Cherry picked from commit 76b72680017c836eff8805ea0339f7827ba3e561:
> Bug Id: 1128165
> Change-Id: I3882e34e840ed15b5ce48ed5e1ad51208e2be913
> Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
> Reviewed-on: http://review.gluster.org/8438
> Tested-by: Gluster Build System <jenkins@build.gluster.com>
> Reviewed-by: Niels de Vos <ndevos@redhat.com>

BUG: 1173515
Change-Id: I3882e34e840ed15b5ce48ed5e1ad51208e2be913
Signed-off-by: Niels de Vos <ndevos@redhat.com>
Reviewed-on: http://review.gluster.org/9271
Tested-by: Gluster Build System <jenkins@build.gluster.com>
Reviewed-by: Vijay Bellur <vbellur@redhat.com>

diff --git a/xlators/mount/fuse/utils/mount.glusterfs.in b/xlators/mount/fuse/utils/mount.glusterfs.in
--- a/xlators/mount/fuse/utils/mount.glusterfs.in
+++ b/xlators/mount/fuse/utils/mount.glusterfs.in
@@ -267,6 +267,11 @@ start_glusterfs ()
     cmd_line=$(echo "$cmd_line $mount_point");
     err=0;
     $cmd_line;
+    if [ $? -ne 0 ]; then
+        echo "Mount failed. Please check the log file for more details."
+        exit 1;
+    fi
+
 
 
     inode=$( ${getinode} $mount_point 2>/dev/null);
