Throwing an error while mounting glusterfs when fuse is not installed.
Signed-off-by: Junaid <junaid@gluster.com>
Signed-off-by: Anand V. Avati <avati@dev.gluster.com>

BUG: 2002 (Mount fails, but gives no error)
URL: http://bugs.gluster.com/cgi-bin/bugzilla3/show_bug.cgi?id=2002

diff --git a/xlators/mount/fuse/utils/mount.glusterfs.in b/xlators/mount/fuse/utils/mount.glusterfs.in
--- a/xlators/mount/fuse/utils/mount.glusterfs.in
+++ b/xlators/mount/fuse/utils/mount.glusterfs.in
@@ -120,16 +120,25 @@ start_glusterfs ()
     fi
 
     cmd_line=$(echo "$cmd_line $mount_point");
+    err=0;
     $cmd_line;
 
     # retry the failover
     if [ $? != "0" ]; then
+        err=1;
         if [ -n "$cmd_line1" ]; then
             cmd_line1=$(echo "$cmd_line1 $mount_point");
             $cmd_line1
+            if [ $? != "0"]; then
+                err=1;
+            fi
         fi
     fi
 
+    if [ $err -eq "1" ]; then
+            echo "Mount failed. Please check the log file for more details."
+            exit 1;
+    fi
 }
 
 usage ()
