mount: Verify mount failure in mount.glusterfs wrapper.
The result of mount command execution is not checked properly, thus
no proper message given for the end user. This patch fix the same.

Bug Id: 1128165
Change-Id: I3882e34e840ed15b5ce48ed5e1ad51208e2be913
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
Reviewed-on: http://review.gluster.org/8438
Tested-by: Gluster Build System <jenkins@build.gluster.com>
Reviewed-by: Niels de Vos <ndevos@redhat.com>

diff --git a/xlators/mount/fuse/utils/mount.glusterfs.in b/xlators/mount/fuse/utils/mount.glusterfs.in
--- a/xlators/mount/fuse/utils/mount.glusterfs.in
+++ b/xlators/mount/fuse/utils/mount.glusterfs.in
@@ -297,6 +297,11 @@ start_glusterfs ()
     cmd_line=$(echo "$cmd_line $mount_point");
 
     $cmd_line;
+    if [ $? -ne 0 ]; then
+        warn "Mount failed. Please check the log file for more details."
+        exit 1;
+    fi
+
 
     inode=$( ${getinode} $mount_point 2>/dev/null);
     # this is required if the stat returns error
